[window]
opacity = 0.9

padding.x = 10
padding.y = 0

decorations = "Full"
decorations_theme_variant = "Dark"


[font]

normal.family = "OpenDyslexicM"
bold.family = "OpenDyslexicM"
italic.family = "OpenDyslexicM"
bold_italic.family = "OpenDyslexicM"

size = 15.0
