[window]
opacity = 0.9

padding.x = 10
padding.y = 0

decorations = "Full"
decorations_theme_variant = "Dark"


[font]
normal.family = "OpenDyslexicM Nerd Font Mono"
bold.family = "OpenDyslexicM Nerd Font Mono"
italic.family = "OpenDyslexicM Nerd Font Mono"
bold_italic.family = "OpenDyslexicM Nerd Font Mono"

size = 15.0
